apiVersion: v1
kind: Endpoints
metadata:
  name: cd-mongodb
  namespace: monitoring
  labels:
    k8s-app: cd-mongodb
subsets:
  - addresses:
      - ip: 172.27.240.144 
      - ip: 172.27.241.141
      - ip: 172.27.242.19
    ports:
      - name: jmx
        port: 9001
        protocol: TCP