apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    k8s-app: mongodb
# Add mongo instances IP
subsets:
  - addresses:
      - ip: <ip-1> 
      - ip: <ip-2>
      - ip: <ip-3>
    ports:
      - name: jmx
        port: 9001
        protocol: TCP