apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb-nodeexporter
  namespace: monitoring
  labels:
    k8s-app: mongodb-nodeexporter
subsets:
  # Add mongo instances IP
  - addresses:
      - ip: <ip-1>
      - ip: <ip-2>
      - ip: <ip-3>
    ports:
      - name: jmx
        port: 9100
        protocol: TCP