apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  namespace: monitoring
  labels:
    k8s-app: mongodb
    release: prometheus-operator
spec:
  scrapeTimeout: 120s
  selector:
    matchLabels:
      k8s-app: mongodb
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: jmx
    interval: 90s
    scrapeTimeout: 60s